### ISSUE TITLE
Red Discord Bot Cog Support

### ISSUE THREAD

**Issue by neocharles** [jaredallard/miku#42]
This would be great if you could work on creating this as a cog for the Red discord bot framework:
(https://docs.discord.red/en/stable/guide_cog_creation.html)

**Comment by jaredallard** [comment]
Thanks for the idea, I'm not entirely sure how this would work given that seems to be a Python-specific Discord bot framework. If there's support for Go, I'd be interested in looking further! Let me know if I'm missing anything.
